name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17-ea
          distribution: zulu
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Live documentation with Maven
        run: mvn -B verify --file pom.xml
